### ISSUE TITLE
Drag Rotate Manipulator falsely detecting more than one axis?

### ISSUE THREAD

**Issue by lehthanis** [X-Plane/XPlane2Blender#448] opened 2019-08-02 04:17 UTC
I have a manipulator that is a switch cover. I wanted to use a drag rotate manipulator which I have multiple being used properly.  This switch cover rotates on the Y axis, but the switch itself is rotated 1.88 degrees along X to match the slight angle of the side console.

So the cover is sitting at rotation: 1.88, 0, 0

keyframe at 0 is local y rotation of 0 degrees.  keyframe at 100 is local y rotation of 86 degrees.

I'm thinking the error is because of the rotation being on local y instead of y?  But that seems like a bizarre and very limiting requirement. so I'm thinking it must be a bug? Surely the intent isn't for drag rotate to only function on exact axis?

To replicate, create a cube and rotate it 1.88 along x...then animate it about 90 degrees on local y from like 0 to 86.  Has to be local y though, not y.  Then of course apply a drag rotate manipulator to it.

3.5.1

**Comment by lehthanis** [comment] 2019-08-02 04:25
Testing...zeroing the 1.88 X rotation fixes the error, but of course now it's not lined up right.

**Comment by tngreene** [comment] 2019-08-05 13:15
Can you give me a small test case that reproduces this?

**Comment by lehthanis** [comment] 2019-08-05 14:42
Certainly.  If this isn't allowed, That's fine, but this does it.  I haphazardly chose a random float dataref...probably should spend more time on the choice of dataref, maybe a planemaker slider or something, but I usually custom code these datarefs for the covers.

[OffAxisDragRotate.zip](https://github.com/X-Plane/XPlane2Blender/files/3468079/OffAxisDragRotate.zip)

**Comment by arb65912** [comment] 2019-08-05 14:44
have you tried animate with bones?

**Comment by lehthanis** [comment] 2019-08-06 02:21
@arb65912 nope, didn't think I needed to.

**Comment by tngreene** [comment] 2019-10-03 22:01
What happened? Did you figure it out?

**Comment by lehthanis** [comment] 2019-10-03 22:04
I never figured it out, I just have it no longer tilted on that second axis
for the time being. Did I ever send you a sample case? Do you need one?

**Comment by tngreene** [comment] 2019-10-03 22:06
You did and I never got a chance to look at it and I probably won't for the foreseeable future. I realized that it was a long time since I checked in on this one so I figured at the least I'd ask.

**Comment by lehthanis** [comment] 2020-06-18 14:09
@tngreene I'm still getting this error again:
ERROR: Drag Rotate manipulator attached to RudderTrimManip can only rotate around 1 axis
![Screenshot_2020-06-18_10-06-25_1920x1080](https://user-images.githubusercontent.com/4234630/85030462-7b72b500-b14b-11ea-86e2-25bf779eae7a.png)
In this screenshot, the green cylinder rotates around the local Z axis and is setup using a ZXY euler controller as is also visible.  It's only rotating around the one axis, but it won't export. This is a much more drastic angle, so I can't just straighten it out like the 1.88 degree of the previous example. Is this kind of manipulator not possible?

**Comment by tngreene** [comment] 2020-06-18 14:59
I'm guessing the issue is that 51.6 degrees rotation in the X-Axis. Even though it has no keyframes, the exporter has to take it into account. Axis Angle rotation mode may solve this.... otherwise you could try to parent it to some empty that has the 51.6 degree rotation and then the manipulator once again only has one axis of rotation. I'm forgetting the best thing here, sorry.

**Comment by lehthanis** [comment] 2020-06-18 16:09
Parenting it to an empty at 51.6 worked beautifully.  Is this going to be a permanent workaround solution or is this type of rotation something that can eventually be supported without the need for empty?

**Comment by lehthanis** [comment] 2020-06-18 17:02
I don't think so...I don't use any bones. Empties animate just like any other geometry and can have datarefs applied to them.  My control sticks are built like that.  I use an empty animated in the pitch axis with an animation dataref applied...and then I add the stick geometry as a child of that empty and animate it in the roll axis and apply the dataref to it the same as pitch.

I usually duplicate this and set a nodraw physical geometry for the manipulator in the cockpit obj with dragXY manip setup.

**Comment by arb65912** [comment] 2020-06-18 17:17
Thank you Robbie!

I will need to try that.
I was using bones as since I started using exporter it seemed to be the only way of animating objects with rotation axes not parallel/perpendicular to X-Plane axes (Global UCS axes in Blender)

**Comment by tngreene** [comment] 2020-10-28 20:33
Closed for lack of activity - I've lost track over if this is a bug or not. If there is something unsolved tell me!

**Closed by tngreene** 2020-10-28 20:33 UTC
Labels: in review
