### ISSUE TITLE
spot_params_bb_pm exporting the old way

### ISSUE THREAD

**Issue by Cristiano-Maggi** [X-Plane/XPlane2Blender#699] opened 2022-04-22 17:28 UTC
The parameterized photometric billboards are being exporting with the OLD dx dy dz width scheme by io_xplane2blender_4_2_0-rc_2-117_20220419015723-v12.
"spot_params_sp_pm" and "spot_params_bb_pm" in the same position should have matching values but they don't.
Example:
`LIGHT_PARAM	spot_params_sp_pm 24.988914 23.926901 80.047714 1 0.82278591 0.52711523 1 15000cd -0.32809913 -0.28239337 -0.90144604 0.64278761`
`LIGHT_PARAM	spot_params_bb_pm 24.988914 23.926901 80.047714 1 0.82278591 0.52711523 15000cd -0.91849875 -0.79054749 -2.5235577 -1.7994549`

**Comment by bsupnik** [comment] 2023-02-25 19:40
@Cristiano-Maggi I cannot reproduce this on the very latest 4.2.0 code.  I'll cut RC3 shortly, then please re-test this and we can close it if it really is fixed, or I'll investigate more if you can still see it. 

I suspect your fixing the lights.txt file a few months ago is what fixed this.

**Comment by Cristiano-Maggi** [comment] 2023-02-26 09:55
I can confirm that both the lights are identically exported now

**Closed** 2023-02-26 09:55 UTC
