### ISSUE TITLE
Objects transformed with "Object/Mirror" export with their Normals Inside/Out

### ISSUE THREAD

**Issue by KarlLeclerc** [X-Plane/XPlane2Blender#601] opened 2020-10-23 23:39 UTC
You can get the same results repeatedly by using the following process:
- Create an object (a shaped cylinder will make it obvious)
- Go to Edit Mode
- Select all vertices
- Move all vertices along the X-axis so that the point of origin is outside of the vertices
- Back to object mode
- Duplicate the object
- With the duplicate selected, using the object mode menu, click on "Object", "Mirror", then "X-Global". This will create a mirror image of the original object on the X-axis (with the same point of origin)
- Save and Export to X-Plane by attaching to your favourite aircraft

The original object has the correct normals, while the mirrored object has its normals inside/out.

The only solution I found to display the mirrored object properly in X-Plane is to flip the normals outside/in in Blender.

**Comment by KarlLeclerc** [comment] 2020-10-24 00:41
I should add that both objects show correct normals in Blender. Only in X-Plane will the mirrored object show that its normals are incorrect.

**Comment by arb65912** [comment] 2020-10-24 00:43
OK, I understand. Thanks!
I always Apply Mirror Modifier before exporting so never had a chance to experience it.

**Comment by tngreene** [comment] 2020-10-28 21:19
Hi,
Thank you for your detailed explanation! Is this the case you're talking about?
[mirroed_x_example.zip](https://github.com/X-Plane/XPlane2Blender/files/5454888/mirroed_x_example.zip)

**Comment by KarlLeclerc** [comment] 2020-10-29 01:34
Exactly. Same issue. After adding materiel and making it a root collection, I exported the two cylinders you made, attached them to my helicopter, and ended up with the same unwanted results: while the mirrored cylinder's normals are correct in Blender, they export inside/out in X-Plane.  The original cylinder remains correct in both.

Hope this helps.

Thanks for everything you do.

**Comment by DWmFrancis** [comment] 2020-10-29 11:12
Now that you mention it, I’ve seen 
this behavior as well, although in a different context. I had imported a CAD model of a Ford GT-40 to use as scenery and noticed that although the sense of the normals was correct in Fusion 360, once I brought it out of Blender into X-Plane the orientation of some of the normals had flipped, so some of the body panels appeared transparent. I never figured out how to fix it. I thought perhaps it was a glitch in the original CAD model, but now I’m not so sure.

-df

**Comment by tngreene** [comment] 2020-10-29 14:35
What Blender and XPlane2Blender versions are you using?

**Comment by DWmFrancis** [comment] 2020-10-29 14:40
Ted -

This was a few weeks ago, so the Blender version would have been 2.80 wish and the XPlane to Blender version would’ve been pre 4.0.

Should I try again with the updated versions?

~ df

801-518-1829

http://thinkingofdesign.blogspot.com or
http://arrowdevelopment.blogspot.com

**Comment by tngreene** [comment] 2020-10-29 14:55
No, I don't think so. I've stepped through the code in 2.80, 2.81 and then 2.79 - its definitely a Blender bug. When we take the mesh and calculate the loop triangles it gets messed up.

Until it gets fixed I recommend a different way to mirror objects - like the Mirror modifier which I can confirm works before and after you hit apply.

**Comment by tngreene** [comment] 2020-10-29 15:11
Frustratingly it appears other people have reported this before and the Blender team hasn't been historically interested in fixing the bad UI. I'm not sure on their position or progress now, I'll re-file the bug that this is bad behavior.

https://developer.blender.org/T5940
https://developer.blender.org/T35293

The solution some developers have proposed is that after a mirror operation you should flip or recalc the normals so the underlying data is correct to match the UI.

**Comment by KarlLeclerc** [comment] 2020-10-29 15:33
Currently using Blender 2.83.8 (Long Term Support), but the issue has existed as far back as 2.79 at least. I have been reluctant to upgrade to 2.90 in order to maintain stability during the project. If someones tells me that 2.9X fixes the issue, I may copy everything and try it. In the mean time, I can just flip the normals outside/in for mirrored objects, but as I am nearing the end of the 3D modelling phase, there are a few of them...

That I could tell, XP2B versions 4b2 to 4rc1 did not change anything for that issue.

Thanks for the follow-up and for filing with Blender. Their bug reporting is not as easy...

Cheers.

**Comment by arb65912** [comment] 2020-10-29 16:51
My solution was like described below and never had a problem with mirrored mesh, regardless of version of Blender.
I am using Blender 2.83.8 LTS as well as 1.60 gave me problems, "Last Operation Adjust" window was greyed out for example.

My method:
1. Make a copy of object to mirror (Shift +D), Alt+P (unparent in parented)

2. Mirror along X (Ctrl + M)-> X
3 Apply Rotation and Scale (Ctrl+A)
4. Tab to edit mode, select all and flip vertices
5 Export

**Comment by tngreene** [comment] 2020-10-29 18:00
Wish us luck. https://developer.blender.org/T82228 I tried my best and hope I did it correctly. Seems to be a harsh crowd over there, but, they have a lot to sort through quickly. If they don't get back to me with good news or close it this'll get closed too.

**Comment by KarlLeclerc** [comment] 2020-10-29 20:11
Thanks for filing Ted. I provided support to your report on the Blender site. We'll see what we get...

**Comment by KarlLeclerc** [comment] 2020-10-30 10:55
Hi Ted. This morning, I woke up with an e-mail reply from Blender:

_"In Blender, when an object has an inverted matrix (1 or all 3 scale axes are negative) the "front face" becomes the "back side" of the face.
That is, the render considers that the positive normal is now negative.
If you apply the scale (Shift A) you will see this change in the orientation of the faces.
The normal line seen in edit mode reflects this.

So this is by design and is the expected behavior.
If this behavior is changed it will also have its inconveniences.

Closing since this is not a bug, but thank for reporting anyway!"_

Obviously not the outcome we were hoping for. I understand that you can't do anything about it and will want to close the issue. However, I would recommend that you include a statement about the behaviour in your documentation before doing so. If anything, it will prevent someone from scratching their head, blaming the exporter, ... or bugging you.

Thanks for your support.

Karl

**Comment by tngreene** [comment] 2020-10-30 13:07
Well, all I can do that this point is calmly accept their resolution and not get mad at what I think is obviously the wrong choice. ....Not very satisfying. Maybe it can be written down somewhere, or the next person who needs to know this will find this bug! Thank you for bringing it up with such a great bug report!

**Closed by tngreene** 2020-10-30 13:07 UTC
Labels: in review

**Comment by DWmFrancis** [comment] 2020-10-31 03:57
I seem to recall there being a command to reorient all the normals in the same direction.  Does that not work in this case?

=df

**Comment by KarlLeclerc** [comment] 2020-10-31 10:10
You can use many tools to flip the normals (recalculate, flip normals, vertices...), but at the end, if you transformed the object with "Object/Mirror", it will only display properly after exporting to X-Plane if the face orientation was flipped (red instead of blue) in Blender.
