### ISSUE TITLE
Import error on running tests

### ISSUE THREAD

**Issue by Tarcontar** [X-Plane/XPlane2Blender#468] opened 2019-08-29 07:08 UTC
Hi,
I am trying to run the tests with "python3 tests.py" inside the project folder. 
But I get an error at the first file in tests/addon/addon.test.py 
    from io_xplane2blender.tests Import * -> no module named io_xplane2blender

Am I using the wrong python Version or something? With python 2 it does not work for me eather because of the "def main(argv=None)->int:" stuff.

Greetings 
Tarcontar

**Comment by tngreene** [comment] 2019-08-29 13:31
Python2 will **Definitely** not work!

The issue is that Blender has to load the addon in order to run its code, and to load the addon it has to be in the 2.79/scripts/addons folder.

The tests folder also has to be in that folder for Python import reasons, even though it isn't addon (its fine by Blender)

I've found two ways to do this:
1. Clone the git repo into `AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`, but this is messy and it isn't where I'd like my code projects to be
2. Clone the git repo somewhere else and (if you're on Windows) make a Junction Link inside the addons folder to the two important directories `io_xplane2blender` and `tests`.

Then, when you're in the git repo, run the test runner script as normal. Blender will have the addon registered, tests will be in the correct place, and the Junction link makes the whole thing invisible to Blender. It really simply believes that `io_xplane2blender` is in the addons folder.

I don't know what the Mac or Linux replacement is, Blender doesn't follow shortcut links on Windows.

My output of dir
```
 Directory of C:\Users\Ted\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons

08/15/2019  04:34 PM    <DIR>          .
08/15/2019  04:34 PM    <DIR>          ..
06/11/2019  02:47 PM    <JUNCTION>     io_xplane2blender [C:\Users\Ted\XPlane2Blender\io_xplane2blender]
10/16/2018  11:26 AM    <JUNCTION>     tests [C:\Users\Ted\XPlane2Blender\tests]
```

See this article if you're on Windows about [Junction Links](https://www.computerhope.com/jargon/j/junction.htm).

Once again, to be clear, io_xplane2blender is the folder with the addon, XPlane2Blender is the project folder. Blender only knows how to detect the addon folder.

[Installation Guide](https://xp2b-docs.gitbook.io/xplane2blender-docs/index-3/34_installation)

**Comment by Tarcontar** [comment] 2019-08-29 18:56
Hi, thx a lot for that very detailed answer.
Got it to work now!

Tarcontar

**Comment by tngreene** [comment] 2019-08-29 21:24
Oh good! I'm very glad. Make sure to read the --help for the test runner because I've programmed some very useful options (I think) like --print-fails and --start-at

**Closed by tngreene** 2019-08-29 21:24 UTC
